# Jekyll Confit

title: Christmas Elf
author: Lee Marsden
email: me@phz3.net
description: 'Yada Bada'
year: 2017
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.christmaself.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
permalink: /posts/:title

include: ["_pages", "_products"]

# Exclude
exclude:
  - package.json
  - README.md
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - node_modules
  - assets
  - yarn-error.log
  - postcss.config.js
  - webpack.config.babel.js

# Keep
keep_files:
  - assets