# Jekyll Confit

title: Kickstart Static
author: Lee Marsden
email: me@phz3.net
description: 'Yada Bada'
year: 2017
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

include: ["_pages"]

# Exclude
exclude:
  - package.json
  - README.md
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - node_modules
  - assets
  - yarn-error.log
  - postcss.config.js

# Keep
keep_files:
  - assets